name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.21.0'

    - name: Lint
      uses: Jerome1337/golint-action@v1.0.2

    - run: docker pull hello-world

    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out ./...
      env:
        TEST_DB_CONN_STRING: "user=postgres password=postgres dbname=tests sslmode=disable port=5432 host=localhost"
        TEST_DB_URL: "postgres://postgres:postgres@localhost:5432/tests?sslmode=disable"
        HELLO_CONTAINER: "hello-world"
